export const API_URL = 'https://api.unsplash.com';
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = "https://unsplash.com/oauth/token";
export const API_URL_AUTH = "https://unsplash.com/oauth/authorize";
export const ACCESS_KEY = "R2uTX0xZCNHnc0DTBghe9mKHvtZEXroH40UkKES7EbE";
export const SECRET_KEY = "dTEN7JCzLKDLqywE62i5qQ5s3B6H9xOXk91lhA7Vf-4";
export const REDIRECT_URI = 'http://127.0.0.1:5505/';
export const RESPONSE_TYPE = 'code';
export const SCOPE = 'public read_user read_photos write_likes';